### ISSUE TITLE
[cloud_firestore] isEqualTo matches against null

### ISSUE THREAD

**Issue by greghesp** [invertase/flutterfire#17]
[Original Issue](https://github.com/FirebaseExtended/flutterfire/issues/691)
[YouTrack](https://yt.invertase.io/youtrack/agiles/116-4/117-4?query=Module:%20%7BCloud%20Firestore%7D%20%20https:%2F%2Fgithub.com%2FFirebaseExtended%2Fflutterfire%2Fissues%2F691&issue=FF-341)

Can replicate

```dart
return StreamBuilder<QuerySnapshot>(
        stream: users.where("uid", isEqualTo: null).snapshots(),
```
returns all documents in collection, even if field uid is set to null in at least one document.

![image](https://user-images.githubusercontent.com/768908/84153148-6d42db80-aa5d-11ea-81ec-9223b2748d7b.png)
![image](https://user-images.githubusercontent.com/768908/84153180-759b1680-aa5d-11ea-8204-7f81d999adc2.png)

**Comment by Ehesp** [comment]
Closing: https://github.com/FirebaseExtended/flutterfire/issues/691#issuecomment-641786240

This would make sense to keep as is looking at the code, since all of the other filter types don't accept `null`, allowing `isEqual` to accept it would be confusing & potentially cause unwanted behaviour.
